# Generated by Django 3.1.8 on 2021-04-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20210419_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ('-rank', 'role', 'pk')},
        ),
        migrations.AlterField(
            model_name='credit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('caption', models.TextField(blank=True)),
                ('rank', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
            options={
                'ordering': ('-rank', 'caption', 'pk'),
            },
        ),
    ]
